version: '3.3'

services:

  build:
    image: docker.io/slobentanzer/biocypher-base:1.0.0
    container_name: build
    volumes:
      - ./config/biocypher_docker_config.yaml:/usr/app/config/biocypher_config.yaml
      - biocypher_data:/usr/app/data
      - biocypher_logs:/usr/app/biocypher-log
      - .:/usr/app/
    environment:
      BIOCYPHER_GITHUB_PROJECT_TOKEN: ${BIOCYPHER_GITHUB_PROJECT_TOKEN}
    command:
      - /bin/bash
      - /usr/app/scripts/build.sh

  import:
    image: neo4j:4.4-enterprise
    container_name: import
    env_file:
      - envs/import.env
    volumes:
      - biocypher_data:/data
      - ./scripts/import.sh:/scripts/import.sh
    command:
      - /bin/bash
      - /scripts/import.sh
    depends_on:
      build:
        condition: service_completed_successfully

  deploy:
    image: neo4j:4.4-enterprise
    container_name: deploy
    volumes:
      - biocypher_data:/data
    env_file:
      - envs/deploy.env
    environment:
      NEO4J_dbms_security_auth__enabled: "false"
      NEO4J_dbms_databases_default__to__read__only: "true"
      # NEO4J_browser_remote__content__hostname__whitelist: "*"
      # NEO4J_browser_post__connect__cmd: "play https://meta-graph-guide.web.app/index.html"
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    depends_on:
      import:
        condition: service_completed_successfully
volumes:
    biocypher_data:
    biocypher_logs:
    biocypher_html:
  # guide:
  #   image: nginx:alpine
  #   volumes:
  #     - ./html:/usr/share/nginx/html
  #   ports:
  #     - "8080:80"