version: '3.3'

services:

  biocypher-builder:
    build:
      context: .
      dockerfile: Dockerfile-bc
    container_name: biocypher-meta-graph
    volumes:
      - ./data:/usr/app/data
    healthcheck:
      test: ["CMD-SHELL", "[ -f ./data/neo4j/neo4j-admin-import-call.sh ] || exit 1"]
      interval: 1s

  neo4j-builder:
    build:
      context: .
      dockerfile: Dockerfile-neo
    container_name: biocypher-meta-graph-builder
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    volumes:
      - ./data:/data
    depends_on:
      biocypher-builder:
        condition: service_healthy

  # neo4j-reader:
  #   image: neo4j:4.4-enterprise
  #   container_name: biocypher-meta-graph-reader
  #   volumes:
  #     - ./data:/data
  #   environment:
  #     NEO4J_AUTH: none
  #     NEO4J_dbms_databases_default__to__read__only: true
  #     NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  #   ports:
  #     - "127.0.0.1:55:7474"
  #     - "127.0.0.1:56:7687"
  #   command: neo4j
  #   depends_on:
  #     - neo4j-builder