version: '3.3'

services:

  build:
    image: docker.io/andimajore/biocyper_base:python3.10
    container_name: build
    volumes:
      - ./config/biocypher_docker_config.yaml:/usr/app/config/biocypher_config.yaml
      - .:/usr/app
    command:
      - /bin/bash
      - -c
      - |
        cd /usr/app
        rm -rf data
        poetry config virtualenvs.create false
        poetry install
        python3 create_knowledge_graph.py

  import:
    image: neo4j:4.4-enterprise
    container_name: import
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      FILL_DB_ON_STARTUP: "yes"
    volumes:
      - ./data:/data
      - ./data/build2neo/neo4j-admin-import-call.sh:/usr/import.sh
    command:
      - /bin/bash
      - -c
      - |
        if [ -f /usr/import.sh ]; then
          chmod +x /usr/import.sh
          /usr/import.sh
        fi
        neo4j start
        sleep 10
        neo4j stop
    depends_on:
      build:
        condition: service_completed_successfully

  deploy:
    image: neo4j:4.4-enterprise
    container_name: deploy
    volumes:
      - ./data:/data
    environment:
      NEO4J_dbms_security_auth__enabled: "false"
      NEO4J_dbms_databases_default__to__read__only: "true"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_browser_post__connect__cmd: "play https://raw.githubusercontent.com/biocypher/meta-graph/read_only/hello.html"
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"
    depends_on:
      import:
        condition: service_completed_successfully